server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot_001?serverTimeZone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: UserProvider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10087/eureka,http://localhost:10086/eureka